services:
  # 1. Base de Datos para AUTH (Usuarios)
  emr-postgres:
    image: postgres:15
    container_name: emr-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: emr_auth_db
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emr-network

  # 2. Redis - Cache
  emr-redis:
    image: redis:7-alpine
    container_name: emr-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - emr-network

  # 3. RabbitMQ - Mensajería
  emr-rabbitmq:
    image: rabbitmq:3-management
    container_name: emr-rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - emr-network

  # ❌ MONGODB ELIMINADO

  # ✅ 4. DynamoDB Local (NUEVO) - PUERTO 8000
  dynamodb-local:
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamo-local
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
    networks:
      - emr-network

  # 5. Base de Datos para AGENDA
  emr-postgres-appointments:
    image: postgres:15
    container_name: emr-postgres-appointments
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: appointments_db
    ports:
      - '5436:5432'
    volumes:
      - postgres_appointments_data:/var/lib/postgresql/data
    networks:
      - emr-network

volumes:
  postgres_data:
  postgres_appointments_data:
  # mongo_data: 👈 Eliminamos el volumen de mongo

networks:
  emr-network:
    driver: bridge
